import { LayoutProps } from "@/types/layout.type";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { type FC } from "react";
import "./globals.css";
import ProviderLayout from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout: FC<LayoutProps> = ({ children }: Readonly<{ children: React.ReactNode; }>) => {
  return (
    <html lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderLayout>
          {children}
        </ProviderLayout>
      </body>
    </html>
  );
}

export default RootLayout;